### ISSUE TITLE
Error: Cannot find module 's_index' when serverless enterprise is enabled

### ISSUE THREAD

**Issue by artworx** [sergioramos/serverless-plugin-tree-shake#47]
This is my serverless.yml file: 

```
...
 functions:
    index:
      handler: dist/index.handler
...
```

The deployed Lamba's entry point gets set to `s_index.handler`, but when `serverless-plugin-tree-shake` is enabled, that file is not present in the deployment. 

```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.1
     Framework Version:         2.9.0 (standalone)
     Plugin Version:            4.1.1
     SDK Version:               2.3.2
     Components Version:        3.2.7
```

**Comment by sergioramos** [comment]
thanks for the report, I'm a bit busy right now, but I'll check this out once I have some time.

One thing to check: do you have any plugin compiling the files into `dist/index.js`? If so, is that step happening when you add `serverless-plugin-tree-shake`?

**Comment by artworx** [comment]
I don't have any extra plugins for compiling

This is the minimal serverless.yml I used to reproduce it. 

```
org: artworx
app: demo
service: lambda-demo

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: dev

plugins
  - serverless-plugin-tree-shake

functions:
  hello:
    handler: handler.main
```

As soon as I add `org` and `app` keys to `serverless.yml`, the handler in cloud formation is `s_handler`. 


```
# .serverless/serverless-state.json

          "HelloLambdaFunction": {
            "Type": "AWS::Lambda::Function",
            "Properties": {
              "Code": {
                "S3Bucket": {
                  "Ref": "ServerlessDeploymentBucket"
                },
                "S3Key": "serverless/...
              },
              "Handler": "s_hello.handler",

```

If I remove the `serverless-plugin-tree-shake`, the packaged zip file includes `s_handler`.
