### ISSUE TITLE
Only works when handler is in root folder

### ISSUE THREAD

**Issue by BryanCrotaz** [sergioramos/serverless-plugin-tree-shake#83]
```yaml
functions:
  CheckAuthLambda:
    handler: ./src/check-auth.handler
```
```
 Serverless Error ---------------------------------------

  No file matches include / exclude patterns

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.20.0
     Framework Version:         2.18.0 (local)
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.6
```

Moving `check-auth.ts` up to root folder fixes the problem
